// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Body(cards []templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Radwan's Awesome Blog</title><link rel=\"stylesheet\" href=\"static/style.css\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"></head><body class=\"flex flex-col bg-zinc-900\"><div class=\"h-12 md:h-24\"></div><h1 class=\"group ml-6 mr-6 text-center font-serif text-3xl min-[380px]:text-4xl text-neutral-200 sm:text-5xl md:text-6xl\"><a href=\"\"><span class=\"bg-gradient-to-r from-emerald-400 to-indigo-500 bg-clip-text font-bold text-neutral-200 transition duration-200 group-hover:text-transparent group-hover:duration-200\">Radwan</span> <span class=\"ml-0.5 -mr-1 text-neutral-400\">.</span> <span class=\"text-indigo-500\">Write</span> <span class=\"text-neutral-400\">(</span> <em class=\"text-emerald-400\">\"about computers\"</em> <span class=\"ml-2 text-neutral-400\">)</span></a></h1><div class=\"h-12 md:h-24\"></div><div class=\"ml-12 mr-12 flex flex-wrap justify-center lg:ml-24 lg:mr-24\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, card := range cards {
			templ_7745c5c3_Err = card.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"h-32\"></div><footer class=\"bottom-0 w-full text-center\"><p class=\"text-sm text-neutral-400\">author: literally the header</p><p class=\"text-sm text-neutral-400\"><a href=\"mailto:rjabraouti@outlook.com\">rjabraouti@outlook.com</a></p><p class=\"text-sm text-neutral-400\">built with: love, friendship, and cupcakes </p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
