// Code generated by templ@(devel) DO NOT EDIT.

package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Body(cards []templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<html lang=\"en\"><head><meta charset=\"utf-8\"><title>")
		if err != nil {
			return err
		}
		var_2 := `Radwan's Awesome Blog`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</title><link rel=\"stylesheet\" href=\"static/style.css\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"></head><body class=\"flex flex-col bg-zinc-900\"><div class=\"h-12 md:h-24\"></div><h1 class=\"group ml-6 mr-6 text-center font-serif text-3xl min-[380px]:text-4xl text-neutral-200 sm:text-5xl md:text-6xl\"><a href=\"\"><span class=\"bg-gradient-to-r from-emerald-400 to-indigo-500 bg-clip-text font-bold text-neutral-200 transition duration-200 group-hover:text-transparent group-hover:duration-200\">")
		if err != nil {
			return err
		}
		var_3 := `Radwan`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span><span class=\"ml-0.5 -mr-1 text-neutral-400\">")
		if err != nil {
			return err
		}
		var_4 := `.`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span><span class=\"text-indigo-500\">")
		if err != nil {
			return err
		}
		var_5 := `Write`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span><span class=\"text-neutral-400\">")
		if err != nil {
			return err
		}
		var_6 := `(`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span><em class=\"text-emerald-400\">")
		if err != nil {
			return err
		}
		var_7 := `"about computers"`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</em><span class=\"ml-2 text-neutral-400\">")
		if err != nil {
			return err
		}
		var_8 := `)`
		_, err = templBuffer.WriteString(var_8)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></a></h1><div class=\"h-12 md:h-24\"></div><div class=\"ml-12 mr-12 flex flex-wrap justify-center lg:ml-24 lg:mr-24\">")
		if err != nil {
			return err
		}
		for _, card := range cards {
			err = card.Render(ctx, templBuffer)
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</div><div class=\"h-32\"></div><footer class=\"bottom-0 w-full text-center\"><p class=\"text-sm text-neutral-400\">")
		if err != nil {
			return err
		}
		var_9 := `author: literally the header`
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"text-sm text-neutral-400\"><a href=\"mailto:rjabraouti@outlook.com\">")
		if err != nil {
			return err
		}
		var_10 := `rjabraouti@outlook.com`
		_, err = templBuffer.WriteString(var_10)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a></p><p class=\"text-sm text-neutral-400\">")
		if err != nil {
			return err
		}
		var_11 := `built with: love, friendship, and cupcakes `
		_, err = templBuffer.WriteString(var_11)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></footer></body></html>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
